import {exercises,program} from './data.js';
import {loadState,saveState,workoutKey,exportState,importState} from './state.js';
const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=loadState(),live=null,timerId=null,timerEnds=Number(state.restTimer?.ends||0),durationId=null,audioCtx=null,wakeLock=null;const byId=new Map(exercises.map(x=>[x.id,x]));
const total=program.weeks.reduce((n,w)=>n+w.days.length,0),doneCount=()=>Object.values(state.completed).filter(Boolean).length,fmt=ms=>{const s=Math.max(0,Math.floor(ms/1000)),m=Math.floor(s/60);return `${m}:${String(s%60).padStart(2,'0')}`};
function header(active='training'){return `<header class="header"><button class="brand-home" data-home><div class="brand">RETHINK.</div><div class="brand-sub">GLUTES & CORE</div></button><div class="header-actions"><button class="ghost-link ${active==='history'?'active':''}" data-view="history">VERLAUF</button><button class="ghost-link ${active==='plan'?'active':''}" data-view="plan">PLAN</button></div></header>`}
function nextWorkout(){for(const w of program.weeks)for(let i=0;i<w.days.length;i++)if(!state.completed[workoutKey(w.week,i)])return{w,i,d:w.days[i]};return null}
function preview(items){return `<section class="today-workout"><div class="today-head"><span>HEUTIGES WORKOUT</span><strong>${items.length} ÜBUNGEN</strong></div><div class="today-list">${items.map(([id,p],i)=>`<div class="today-exercise"><span class="today-index">${String(i+1).padStart(2,'0')}</span><div class="today-main"><strong>${esc(byId.get(id)?.name||id)}</strong><small>${esc(p)}</small></div></div>`).join('')}</div></section>`}
function renderTraining(){const n=nextWorkout(),pct=Math.round(doneCount()/total*100);if(!n)return `${header()}<section class="hero complete-home"><div class="kicker">PROGRAMM ABGESCHLOSSEN</div><div class="hero-code">100%</div><h1>Glutes & Core geschafft.</h1><p class="small meta">${total} Einheiten abgeschlossen. Deine Leistungen bleiben im Verlauf gespeichert.</p><button class="primary home-primary" data-view="history">ERGEBNISSE ANSEHEN</button></section>`;const key=workoutKey(n.w.week,n.i),resume=state.activeSession?.key===key;return `${header()}<section class="home-summary"><div class="kicker">WOCHE ${n.w.week} · ${n.i+1}/3</div><h1>${['A','B','C'][n.i]} <span>•</span> ${esc(n.d.name)}</h1><p>${esc(n.w.focus)}</p></section>${preview(n.d.items)}<button class="primary home-primary ${resume?'resume':''}" data-start="${n.w.week}:${n.i}">${resume?'WORKOUT FORTSETZEN':'WORKOUT STARTEN'}</button><section class="home-footer"><div class="home-footer-row"><span>PROGRAMM</span><strong>${doneCount()} / ${total}</strong><span class="home-skill">GLUTES · CORE · FULL BODY</span></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div></section>`}
function renderPlan(){return `${header('plan')}<section class="plan-head"><div class="kicker">13 WOCHEN · 3× PRO WOCHE</div><h1>Glutes & Core.</h1><p class="small">Glute-dominantes Ganzkörperprogramm · ca. 30–45 Minuten pro Einheit.</p><div class="backup-row"><button data-backup>BACKUP ERSTELLEN</button><button data-restore>BACKUP EINLESEN</button><input id="restoreFile" type="file" accept="application/json,.json" hidden></div></section><div class="plan-list">${program.weeks.map(w=>`<article class="week ${w.week===nextWorkout()?.w.week?'current open':''}"><button class="week-head" data-week-toggle><div><div class="kicker">WOCHE ${w.week}</div><h2>${esc(w.title)}</h2><p class="small">${esc(w.focus)}</p></div><span class="week-count">${w.days.filter((_,i)=>state.completed[workoutKey(w.week,i)]).length}/3</span></button><div class="week-days">${w.days.map((d,i)=>{const k=workoutKey(w.week,i),dn=state.completed[k];return `<button class="plan-day ${dn?'done':''}" ${dn?`data-summary="${k}"`:`data-start="${w.week}:${i}"`}><div><strong>${['A','B','C'][i]} · ${esc(d.name)}</strong><span class="tiny">${d.items.reduce((n,x)=>n+parseSets(x[1]),0)} Arbeitssätze</span></div><span>›</span></button>`}).join('')}</div></article>`).join('')}</div>`}
function renderHistory(){const entries=Object.entries(state.summaries).sort((a,b)=>(b[1].finishedAt||0)-(a[1].finishedAt||0));return `${header('history')}<section class="skills-head"><div class="kicker">DEIN VERLAUF</div><h1>${doneCount()} Workouts.</h1><p class="small">Abgeschlossene Einheiten öffnen als kompakte Zusammenfassung.</p></section><div class="plan-list">${entries.length?entries.map(([k,s])=>`<button class="plan-day done" data-summary="${k}"><div><strong>${esc(s.name)}</strong><span class="tiny">${new Date(s.finishedAt).toLocaleDateString('de-DE')} · ${fmt(s.duration)}</span></div><span>›</span></button>`).join(''):'<p class="small">Noch kein Workout abgeschlossen.</p>'}</div>`}
function render(){const a=$('#app');a.classList.toggle('home-mode',state.view==='training');a.innerHTML=state.view==='plan'?renderPlan():state.view==='history'?renderHistory():renderTraining();bind()}
function bind(){$$('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;saveState(state);render()});$$('[data-home]').forEach(b=>b.onclick=()=>{state.view='training';saveState(state);render()});$$('[data-week-toggle]').forEach(b=>b.onclick=()=>b.closest('.week').classList.toggle('open'));$$('[data-start]').forEach(b=>b.onclick=()=>{const[w,i]=b.dataset.start.split(':').map(Number);openWorkout(w,i)});$$('[data-summary]').forEach(b=>b.onclick=()=>showSummary(b.dataset.summary));$('[data-backup]')?.addEventListener('click',backup);$('[data-restore]')?.addEventListener('click',()=>$('#restoreFile').click());$('#restoreFile')?.addEventListener('change',restore)}
function parseSets(p){const m=String(p).match(/^(\d+)×/);return m?+m[1]:1}
function itemFor([id,p],ei,key){const count=parseSets(p),vals=state.setPerformance[`${key}:${ei}`]||[],checks=state.setChecks[`${key}:${ei}`]||[];return{id,x:byId.get(id),p,checks:Array.from({length:count},(_,i)=>!!checks[i]),values:Array.from({length:count},(_,i)=>String(vals[i]??'')),rating:state.ratings[`${key}:${ei}`]}}
function openWorkout(w,i){const week=program.weeks.find(x=>x.week===w),d=week?.days[i];if(!d)return;const key=workoutKey(w,i),saved=state.activeSession?.key===key?state.activeSession:null;live={week:w,index:i,key,name:d.name,focus:week.focus,startedAt:saved?.startedAt||Date.now(),current:saved?.current||0,items:d.items.map((x,ei)=>itemFor(x,ei,key)),restTotal:Number(state.restTimer?.total||90)};state.activeSession={key,startedAt:live.startedAt,current:live.current};saveState(state);document.body.insertAdjacentHTML('beforeend','<div id="workoutRoot" class="workout-root"></div>');renderWorkout();durationId=setInterval(()=>{const e=$('#duration');if(e)e.textContent=fmt(Date.now()-live.startedAt)},1000);tone('start');try{navigator.wakeLock?.request('screen').then(x=>wakeLock=x)}catch{}}
function renderWorkout(){const it=live.items[live.current],all=live.items.every(x=>x.checks.every(Boolean));$('#workoutRoot').innerHTML=`<section class="workout"><div class="workout-top"><button class="close" data-close>×</button><div class="workout-status">GLUTES & CORE · W${live.week}.${live.index+1} · ${live.current+1}/${live.items.length}</div><div class="duration" id="duration">${fmt(Date.now()-live.startedAt)}</div></div><div class="exercise-stage"><div class="exercise-copy"><div class="kicker">${esc(it.x?.cat)}</div><h1>${esc(it.x?.name)}</h1><div class="target-big">${esc(it.p)}</div><div class="cue">${esc(it.x?.cue)}</div></div><div class="sets">${it.checks.map((c,i)=>`<div class="set-row ${c?'checked':''}"><button data-set="${i}">${c?'✓':i+1}</button><input data-value="${i}" value="${esc(it.values[i])}" placeholder="Leistung"></div>`).join('')}</div><div class="rating"><span>BEWERTUNG</span><div><button class="${it.rating===-1?'active':''}" data-rate="-1">ZU SCHWER</button><button class="${it.rating===0?'active':''}" data-rate="0">PASST</button><button class="${it.rating===1?'active':''}" data-rate="1">ZU LEICHT</button></div></div></div><div class="workout-nav"><button data-prev ${live.current===0?'disabled':''}>←</button>${all?'<button class="finish" data-finish>WORKOUT BEENDEN</button>':`<button data-next ${live.current===live.items.length-1?'disabled':''}>WEITER →</button>`}</div></section><div class="rest-mini ${timerEnds>Date.now()?'show':''}" id="restMini"><span>PAUSE</span><strong id="restTime">${Math.max(0,Math.ceil((timerEnds-Date.now())/1000))}s</strong><button data-stop-rest>×</button></div>`;bindWorkout()}
function bindWorkout(){$('[data-close]').onclick=()=>{persist();cleanup();render()};$$('[data-set]').forEach(b=>b.onclick=()=>{const it=live.items[live.current],i=+b.dataset.set;it.checks[i]=!it.checks[i];persist();if(it.checks[i]){startTimer(recommendedRest(it));tone('set')}renderWorkout()});$$('[data-value]').forEach(inp=>inp.oninput=()=>{live.items[live.current].values[+inp.dataset.value]=inp.value;persist()});$$('[data-rate]').forEach(b=>b.onclick=()=>{const it=live.items[live.current];it.rating=+b.dataset.rate;state.ratings[`${live.key}:${live.current}`]=it.rating;saveState(state);renderWorkout()});$('[data-prev]')?.addEventListener('click',()=>{live.current--;persist();renderWorkout()});$('[data-next]')?.addEventListener('click',()=>{live.current++;persist();renderWorkout()});$('[data-finish]')?.addEventListener('click',finish);$('[data-stop-rest]')?.addEventListener('click',()=>stopTimer())}
function recommendedRest(it){return it.x?.cat?.includes('Core')?45:it.x?.cat?.includes('Glutes')||it.x?.cat?.includes('Full Body')?60:60}
function persist(){state.activeSession={key:live.key,startedAt:live.startedAt,current:live.current};live.items.forEach((it,i)=>{state.setChecks[`${live.key}:${i}`]=[...it.checks];state.setPerformance[`${live.key}:${i}`]=[...it.values]});saveState(state)}
function startTimer(sec){stopTimer(false);timerEnds=Date.now()+sec*1000;live.restTotal=sec;state.restTimer={ends:timerEnds,total:sec};saveState(state);timerId=setInterval(updateTimer,250);updateTimer()}
function updateTimer(){const left=Math.max(0,Math.ceil((timerEnds-Date.now())/1000)),e=$('#restTime');if(e)e.textContent=`${left}s`;if(left<=0){stopTimer(false);tone('rest');navigator.vibrate?.([80,50,80,50,120])}}
function stopTimer(hide=true){clearInterval(timerId);timerId=null;timerEnds=0;state.restTimer=null;saveState(state);if(hide)$('#restMini')?.classList.remove('show')}
function finish(){const finishedKey=live.key,duration=Date.now()-live.startedAt,finishedAt=Date.now();state.completed[live.key]=true;state.summaries[live.key]={name:live.name,duration,finishedAt,items:live.items.map(it=>({name:it.x.name,target:it.p,values:[...it.values],rating:it.rating}))};live.items.forEach(it=>{state.performanceHistory[it.id]=[...(state.performanceHistory[it.id]||[]),{date:finishedAt,target:it.p,values:[...it.values],rating:it.rating}].slice(-12)});for(const k of Object.keys(state.setChecks))if(k.startsWith(live.key+':'))delete state.setChecks[k];for(const k of Object.keys(state.setPerformance))if(k.startsWith(live.key+':'))delete state.setPerformance[k];state.activeSession=null;saveState(state);tone('finish');cleanup();render();showSummary(finishedKey)}
function cleanup(){clearInterval(durationId);durationId=null;wakeLock?.release?.();wakeLock=null;$('#workoutRoot')?.remove();live=null}
function showSummary(key){const s=state.summaries[key];if(!s)return;document.body.insertAdjacentHTML('beforeend',`<div id="summaryRoot" class="info-overlay"><div class="info-card summary-card"><button class="close-info" data-summary-close>×</button><div class="kicker">WORKOUT ZUSAMMENFASSUNG</div><h2>${esc(s.name)}</h2><p class="small">${new Date(s.finishedAt).toLocaleDateString('de-DE')} · ${fmt(s.duration)}</p><div class="summary-items">${s.items.map((it,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span><p><strong>${esc(it.name)}</strong><small>${esc(it.target)}${it.values.some(Boolean)?' · '+it.values.map(v=>esc(v||'–')).join(' / '):''}</small></p><em>${it.rating===-1?'zu schwer':it.rating===0?'passt':it.rating===1?'zu leicht':'–'}</em></div>`).join('')}</div></div></div>`);$('[data-summary-close]').onclick=()=>$('#summaryRoot').remove()}
function backup(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(exportState(state),null,2)],{type:'application/json'}));a.download=`RETHINK.GlutesCore.Backup.${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function restore(e){const f=e.target.files?.[0];if(!f)return;try{const p=JSON.parse(await f.text());if(!confirm('Backup einspielen? Aktuelle lokale Daten werden ersetzt.'))return;state=importState(p);state.view='training';saveState(state);render();alert('Backup vollständig eingespielt.')}catch(x){alert('Backup konnte nicht eingelesen werden: '+x.message)}e.target.value=''}
function tone(type){if(!state.sound)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume?.();const now=audioCtx.currentTime,seq=type==='rest'?[[820,0,.2],[980,.25,.2],[1180,.5,.32]]:type==='finish'?[[700,0,.15],[900,.2,.18],[1100,.43,.3]]:[[520,0,.08]];for(const[f,d,u]of seq){const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=now+d;o.type=type==='rest'?'square':'sine';o.frequency.value=f;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(type==='rest'?.32:.15,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+u);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+u+.03)}}catch{}}
async function lockPortrait(){try{await screen.orientation?.lock?.('portrait')}catch{}}
if(timerEnds>Date.now())timerId=setInterval(updateTimer,250);else{state.restTimer=null}state.view='training';saveState(state);lockPortrait();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
