export const exercises=[
{id:'reverse-lunge-drive',name:'Reverse Lunge + Knee Drive',cat:'Glutes · Full Body',level:2,equipment:'Zuhause',muscles:'Glutes · Full Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Großen Schritt zurücksetzen, über den vorderen Fuß hochdrücken und das hintere Knie kontrolliert nach vorn führen.'},
{id:'stepup-drive',name:'Step-up + Knee Drive',cat:'Glutes · Full Body',level:2,equipment:'Zuhause',muscles:'Glutes · Full Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Auf eine stabile Stufe steigen, vollständig über das Arbeitsbein hochdrücken und das freie Knie kontrolliert nach vorn führen.'},
{id:'squat-knee-drive',name:'Squat + Knee Drive',cat:'Glutes · Full Body',level:2,equipment:'Zuhause',muscles:'Glutes · Full Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Tief und kontrolliert beugen, kraftvoll aufrichten und abwechselnd ein Knie nach vorn oben führen.'},
{id:'lateral-lunge-drive',name:'Lateral Lunge + Knee Drive',cat:'Glutes · Full Body',level:2,equipment:'Zuhause',muscles:'Glutes · Full Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Seitlich weit aussteigen, Hüfte über das belastete Bein zurücksetzen und beim Aufrichten das freie Knie anheben.'},
{id:'bulgarian',name:'Bulgarian Split Squat',cat:'Glutes · Legs',level:2,equipment:'Zuhause',muscles:'Glutes · Legs',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Hinteren Fuß auf Sofa oder Stuhl ablegen. Über das vordere Bein kontrolliert tief gehen und hochdrücken.'},
{id:'reverse-lunge',name:'Reverse Lunge',cat:'Glutes · Legs',level:2,equipment:'Zuhause',muscles:'Glutes · Legs',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Einen großen Schritt zurücksetzen, vorderen Fuß voll belasten und über das vordere Bein wieder aufrichten.'},
{id:'stepup',name:'Step-up',cat:'Glutes · Legs',level:2,equipment:'Zuhause',muscles:'Glutes · Legs',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Auf eine stabile Stufe steigen und den Körper ohne Absprung vom Boden vollständig über das Arbeitsbein hochdrücken.'},
{id:'sumo-squat',name:'Sumo Squat',cat:'Glutes · Legs',level:2,equipment:'Zuhause',muscles:'Glutes · Legs',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Breiter Stand, Knie folgen den Fußspitzen. Hüfte kontrolliert absenken und kraftvoll aufrichten.'},
{id:'tempo-squat',name:'Tempo Squat',cat:'Glutes · Legs',level:2,equipment:'Zuhause',muscles:'Glutes · Legs',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Drei Sekunden absenken, unten kurz stabil bleiben und kontrolliert aufrichten.'},
{id:'sl-rdl',name:'Single Leg RDL',cat:'Glutes · Hamstrings',level:2,equipment:'Zuhause',muscles:'Glutes · Hamstrings',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Standbein leicht beugen, Hüfte weit nach hinten schieben und mit langem Rücken über die Hüfte wieder aufrichten.'},
{id:'kickstand-rdl',name:'Kickstand RDL',cat:'Glutes · Hamstrings',level:2,equipment:'Zuhause',muscles:'Glutes · Hamstrings',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Ein Bein trägt fast das gesamte Gewicht, die andere Fußspitze dient nur als Stütze. Hüfte weit nach hinten führen.'},
{id:'hip-thrust',name:'Hip Thrust',cat:'Glutes',level:2,equipment:'Zuhause',muscles:'Glutes',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Schulterblätter an Sofa oder Bettkante. Becken über die Fersen strecken und oben das Gesäß kräftig anspannen.'},
{id:'single-hip-thrust',name:'Single Leg Hip Thrust',cat:'Glutes',level:2,equipment:'Zuhause',muscles:'Glutes',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Schulterblätter erhöht, ein Bein frei. Becken einbeinig strecken und dabei gerade halten.'},
{id:'glute-bridge',name:'Glute Bridge',cat:'Glutes',level:2,equipment:'Zuhause',muscles:'Glutes',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Fersen nah zum Gesäß, Becken anheben und oben Gesäß fest anspannen ohne ins Hohlkreuz zu gehen.'},
{id:'single-bridge',name:'Single Leg Glute Bridge',cat:'Glutes',level:2,equipment:'Zuhause',muscles:'Glutes',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Eine Ferse nah zum Gesäß, anderes Bein frei. Becken gerade einbeinig anheben und oben kurz halten.'},
{id:'frog-pump',name:'Frog Pump',cat:'Glutes',level:2,equipment:'Zuhause',muscles:'Glutes',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Fußsohlen zusammen, Knie nach außen. Becken anheben und jede Wiederholung mit deutlicher Gesäßanspannung beenden.'},
{id:'bridge-march',name:'Glute Bridge March',cat:'Glutes · Core',level:2,equipment:'Zuhause',muscles:'Glutes · Core',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Becken in der Bridge oben halten und abwechselnd einen Fuß wenige Zentimeter anheben, ohne das Becken zu verdrehen.'},
{id:'pushup',name:'Push-up',cat:'Push · Upper Body',level:2,equipment:'Zuhause',muscles:'Push · Upper Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Körper als feste Linie halten. Brust kontrolliert absenken und den Boden aktiv wegdrücken.'},
{id:'incline-pushup',name:'Incline Push-up',cat:'Push · Upper Body',level:2,equipment:'Zuhause',muscles:'Push · Upper Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Hände erhöht auf stabilem Tisch oder Sofa. Körper gerade halten und Brust kontrolliert zur Kante führen.'},
{id:'decline-pushup',name:'Decline Push-up',cat:'Push · Upper Body',level:2,equipment:'Zuhause',muscles:'Push · Upper Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Füße leicht erhöht, Hände am Boden. Körper stabil halten und kontrolliert drücken.'},
{id:'pike-pushup',name:'Pike Push-up',cat:'Push · Upper Body',level:2,equipment:'Zuhause',muscles:'Push · Upper Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Hüfte hochschieben, Kopf kontrolliert zwischen den Händen absenken und den Boden kräftig wegdrücken.'},
{id:'band-row',name:'Resistance Band Row',cat:'Pull · Upper Body',level:2,equipment:'Zuhause',muscles:'Pull · Upper Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Band sicher vor dir fixieren. Ellbogen nach hinten ziehen und Schulterblätter kontrolliert zusammenführen.'},
{id:'band-pulldown',name:'Resistance Band Pulldown',cat:'Pull · Upper Body',level:2,equipment:'Zuhause',muscles:'Pull · Upper Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Band sicher über Kopfhöhe fixieren. Ellbogen nach unten zum Körper ziehen und langsam zurückführen.'},
{id:'band-pullapart',name:'Resistance Band Pull-Apart',cat:'Pull · Upper Body',level:2,equipment:'Zuhause',muscles:'Pull · Upper Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Band auf Brusthöhe halten und mit gestreckten Armen auseinanderziehen, bis die Schulterblätter zusammenkommen.'},
{id:'dead-bug',name:'Dead Bug',cat:'Core Stability',level:2,equipment:'Zuhause',muscles:'Core Stability',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Rücken stabil am Boden halten. Gegengleichen Arm und Bein langsam strecken, ohne dass sich der untere Rücken löst.'},
{id:'side-plank',name:'Side Plank',cat:'Core Stability',level:2,equipment:'Zuhause',muscles:'Core Stability',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Schulter, Becken und Füße in einer Linie halten. Becken aktiv vom Boden wegdrücken.'},
{id:'bear-tap',name:'Bear Plank Shoulder Tap',cat:'Core Stability',level:2,equipment:'Zuhause',muscles:'Core Stability',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Knie knapp über dem Boden halten und abwechselnd die gegenüberliegende Schulter berühren, ohne das Becken zu verdrehen.'},
{id:'plank-drag',name:'Plank Reach',cat:'Core Stability',level:2,equipment:'Zuhause',muscles:'Core Stability',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Aus stabiler Plankposition einen Arm langsam nach vorn strecken. Becken und Brust bleiben möglichst ruhig.'},
{id:'bird-dog',name:'Bird Dog',cat:'Core Stability',level:2,equipment:'Zuhause',muscles:'Core Stability',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Im Vierfüßler gegengleichen Arm und Bein lang ausstrecken, ohne Becken oder Rücken zu verdrehen.'},
];
export const weeks=[
{week:1,date:'',title:'Einstieg',focus:'Technik festigen · 30–35 Min.',days:[
{name:'Glute Squat',items:[['reverse-lunge-drive','3×8/Seite'],['bulgarian','3×8/Seite'],['band-row','3×10–12'],['glute-bridge','3×12–15'],['dead-bug','3×8/Seite']]},
{name:'Glute Hinge',items:[['stepup-drive','3×8/Seite'],['sl-rdl','3×8/Seite'],['incline-pushup','3×10–12'],['hip-thrust','3×12–15'],['side-plank','3×30–45 s/Seite']]},
{name:'Glute + Core',items:[['squat-knee-drive','3×8/Seite'],['reverse-lunge','3×8/Seite'],['band-pulldown','3×10–12'],['frog-pump','3×12–15'],['bird-dog','3×8/Seite']]},
]},
{week:2,date:'',title:'Einstieg +',focus:'Bewegungen festigen · 30–35 Min.',days:[
{name:'Glute Squat',items:[['stepup-drive','3×8–10/Seite'],['bulgarian','3×8–10/Seite'],['incline-pushup','3×10–12'],['single-bridge','3×12–15'],['dead-bug','3×8–10/Seite']]},
{name:'Glute Hinge',items:[['reverse-lunge-drive','3×8–10/Seite'],['kickstand-rdl','3×8–10/Seite'],['band-row','3×10–12'],['hip-thrust','3×12–15'],['side-plank','3×30–45 s/Seite']]},
{name:'Glute + Core',items:[['lateral-lunge-drive','3×8–10/Seite'],['sumo-squat','3×8–10/Seite'],['band-pulldown','3×10–12'],['frog-pump','3×12–15'],['bear-tap','3×8–10/Seite']]},
]},
{week:3,date:'',title:'Aufbau I',focus:'Volumen und Wiederholungen steigern · 35–40 Min.',days:[
{name:'Glute Squat',items:[['reverse-lunge-drive','3×10/Seite'],['bulgarian','3×10/Seite'],['band-row','3×10–15'],['single-bridge','3×12–15'],['dead-bug','3×10/Seite']]},
{name:'Glute Hinge',items:[['stepup-drive','3×10/Seite'],['sl-rdl','3×10/Seite'],['pushup','3×10–15'],['hip-thrust','3×12–15'],['side-plank','3×30–45 s/Seite']]},
{name:'Glute + Core',items:[['squat-knee-drive','3×10/Seite'],['reverse-lunge','3×10/Seite'],['band-pulldown','3×10–15'],['frog-pump','3×12–15'],['bear-tap','3×10/Seite']]},
]},
{week:4,date:'',title:'Aufbau I',focus:'Saubere Progression · 35–40 Min.',days:[
{name:'Glute Squat',items:[['stepup-drive','3×10/Seite'],['bulgarian','3×10–12/Seite'],['pushup','3×10–15'],['single-bridge','3×12–15'],['plank-drag','3×10/Seite']]},
{name:'Glute Hinge',items:[['reverse-lunge-drive','3×10/Seite'],['sl-rdl','3×10–12/Seite'],['band-row','3×10–15'],['hip-thrust','3×12–15'],['side-plank','3×30–45 s/Seite']]},
{name:'Glute + Core',items:[['lateral-lunge-drive','3×10/Seite'],['sumo-squat','3×10–12/Seite'],['band-pulldown','3×10–15'],['bridge-march','3×12–15'],['dead-bug','3×10/Seite']]},
]},
{week:5,date:'',title:'Aufbau I+',focus:'Glute-Hauptübungen priorisieren · 35–40 Min.',days:[
{name:'Glute Squat',items:[['squat-knee-drive','3×10–12/Seite'],['bulgarian','3×10–12/Seite'],['band-row','3×10–15'],['single-hip-thrust','3×10–12/Seite'],['dead-bug','3×10–12/Seite']]},
{name:'Glute Hinge',items:[['stepup-drive','3×10–12/Seite'],['sl-rdl','3×10–12/Seite'],['pushup','3×10–15'],['hip-thrust','3×10–12/Seite'],['side-plank','3×30–45 s/Seite']]},
{name:'Glute + Core',items:[['reverse-lunge-drive','3×10–12/Seite'],['tempo-squat','3×10–12/Seite'],['band-pulldown','3×10–15'],['frog-pump','3×10–12/Seite'],['bear-tap','3×10–12/Seite']]},
]},
{week:6,date:'',title:'Aufbau II',focus:'Anspruch steigern · 35–40 Min.',days:[
{name:'Glute Squat',items:[['reverse-lunge-drive','3×10–12/Seite'],['bulgarian','3×10–12/Seite'],['pushup','3×10–15'],['single-hip-thrust','3×10–15'],['plank-drag','3×10–12/Seite']]},
{name:'Glute Hinge',items:[['stepup-drive','3×10–12/Seite'],['sl-rdl','3×10–12/Seite'],['band-row','3×10–15'],['single-bridge','3×10–15'],['side-plank','3×30–45 s/Seite']]},
{name:'Glute + Core',items:[['lateral-lunge-drive','3×10–12/Seite'],['tempo-squat','3×10–12/Seite'],['band-pulldown','3×10–15'],['hip-thrust','3×10–15'],['bear-tap','3×10–12/Seite']]},
]},
{week:7,date:'',title:'Aufbau II',focus:'Leistung bestätigen · 35–40 Min.',days:[
{name:'Glute Squat',items:[['stepup-drive','3×12/Seite'],['bulgarian','3×10–12/Seite'],['band-row','3×8–12'],['single-hip-thrust','3×12–15'],['dead-bug','3×10–12/Seite']]},
{name:'Glute Hinge',items:[['reverse-lunge-drive','3×12/Seite'],['sl-rdl','3×10–12/Seite'],['pike-pushup','3×8–12'],['hip-thrust','3×12–15'],['side-plank','3×30–45 s/Seite']]},
{name:'Glute + Core',items:[['squat-knee-drive','3×12/Seite'],['reverse-lunge','3×10–12/Seite'],['band-pulldown','3×8–12'],['bridge-march','3×12–15'],['bear-tap','3×10–12/Seite']]},
]},
{week:8,date:'',title:'Aufbau II+',focus:'Kontrolle unter Ermüdung · 35–40 Min.',days:[
{name:'Glute Squat',items:[['lateral-lunge-drive','3×10–12/Seite'],['bulgarian','3×12/Seite'],['pushup','3×10–15'],['single-bridge','3×12–15'],['plank-drag','3×10–12/Seite']]},
{name:'Glute Hinge',items:[['stepup-drive','3×10–12/Seite'],['sl-rdl','3×12/Seite'],['band-row','3×10–15'],['single-hip-thrust','3×12–15'],['side-plank','3×30–45 s/Seite']]},
{name:'Glute + Core',items:[['reverse-lunge-drive','3×10–12/Seite'],['tempo-squat','3×12/Seite'],['band-pulldown','3×10–15'],['frog-pump','3×12–15'],['dead-bug','3×10–12/Seite']]},
]},
{week:9,date:'',title:'Intensivierung',focus:'Schwierigere Varianten · 40–45 Min.',days:[
{name:'Glute Squat',items:[['reverse-lunge-drive','3×12/Seite'],['bulgarian','3×10–12/Seite'],['decline-pushup','3×8–12'],['single-hip-thrust','3×12–15'],['dead-bug','3×12/Seite']]},
{name:'Glute Hinge',items:[['stepup-drive','3×12/Seite'],['sl-rdl','3×10–12/Seite'],['band-row','3×8–12'],['hip-thrust','3×12–15'],['side-plank','3×40–50 s/Seite']]},
{name:'Glute + Core',items:[['squat-knee-drive','3×12/Seite'],['tempo-squat','3×10–12/Seite'],['band-pulldown','3×8–12'],['single-bridge','3×12–15'],['bear-tap','3×12/Seite']]},
]},
{week:10,date:'',title:'Intensivierung',focus:'Glute-Arbeit priorisieren · 40–45 Min.',days:[
{name:'Glute Squat',items:[['stepup-drive','3×12/Seite'],['bulgarian','3×12/Seite'],['band-row','3×8–12'],['single-hip-thrust','3×12–15'],['plank-drag','3×12/Seite']]},
{name:'Glute Hinge',items:[['reverse-lunge-drive','3×12/Seite'],['sl-rdl','3×12/Seite'],['pike-pushup','3×8–12'],['hip-thrust','3×12–15'],['side-plank','3×40–50 s/Seite']]},
{name:'Glute + Core',items:[['lateral-lunge-drive','3×12/Seite'],['reverse-lunge','3×12/Seite'],['band-pulldown','3×8–12'],['bridge-march','3×12–15'],['dead-bug','3×12/Seite']]},
]},
{week:11,date:'',title:'Intensivierung +',focus:'Stabile Leistung · 40–45 Min.',days:[
{name:'Glute Squat',items:[['squat-knee-drive','3×12/Seite'],['bulgarian','3×12/Seite'],['decline-pushup','3×8–12'],['single-hip-thrust','3×12–15'],['dead-bug','3×12/Seite']]},
{name:'Glute Hinge',items:[['stepup-drive','3×12/Seite'],['sl-rdl','3×12/Seite'],['band-row','3×8–12'],['single-bridge','3×12–15'],['side-plank','3×40–50 s/Seite']]},
{name:'Glute + Core',items:[['reverse-lunge-drive','3×12/Seite'],['tempo-squat','3×12/Seite'],['band-pulldown','3×8–12'],['frog-pump','3×12–15'],['bear-tap','3×12/Seite']]},
]},
{week:12,date:'',title:'Peak',focus:'Höchste saubere Belastung · 40–45 Min.',days:[
{name:'Glute Squat',items:[['reverse-lunge-drive','3×12–15/Seite'],['bulgarian','3×12/Seite'],['band-row','3×10–15'],['single-hip-thrust','3×12–15'],['plank-drag','3×12–15/Seite']]},
{name:'Glute Hinge',items:[['stepup-drive','3×12–15/Seite'],['sl-rdl','3×12/Seite'],['pike-pushup','3×10–15'],['hip-thrust','3×12–15'],['side-plank','3×40–50 s/Seite']]},
{name:'Glute + Core',items:[['lateral-lunge-drive','3×12–15/Seite'],['tempo-squat','3×12/Seite'],['band-pulldown','3×10–15'],['single-bridge','3×12–15'],['bear-tap','3×12–15/Seite']]},
]},
{week:13,date:'',title:'Abschluss',focus:'Fortschritt vergleichen · 35–45 Min.',days:[
{name:'Glute Squat',items:[['reverse-lunge-drive','3×12/Seite'],['bulgarian','3×12/Seite'],['band-row','3×12–15'],['single-bridge','3×15'],['dead-bug','3×12/Seite']]},
{name:'Glute Hinge',items:[['stepup-drive','3×12/Seite'],['sl-rdl','3×12/Seite'],['pushup','3×12–15'],['hip-thrust','3×15'],['side-plank','3×40–50 s/Seite']]},
{name:'Glute + Core',items:[['squat-knee-drive','3×12/Seite'],['reverse-lunge','3×12/Seite'],['band-pulldown','3×12–15'],['frog-pump','3×15'],['bear-tap','3×12/Seite']]},
]},
];
export const intro={title:'',focus:'',days:[]};
export const rules=[];
export const glutesCoreProgram={id:'unused',name:'',subtitle:'',weeks:[]};