export const exercises=[
{id:'reverse-lunge-drive',name:'Reverse Lunge + Knee Drive',cat:'Glutes · Full Body',level:2,equipment:'Zuhause',muscles:'Glutes · Full Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Großen Schritt zurücksetzen, über den vorderen Fuß hochdrücken und das hintere Knie kontrolliert nach vorn führen.'},
{id:'stepup-drive',name:'Step-up + Knee Drive',cat:'Glutes · Full Body',level:2,equipment:'Zuhause',muscles:'Glutes · Full Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Auf eine stabile Stufe steigen, vollständig über das Arbeitsbein hochdrücken und das freie Knie kontrolliert nach vorn führen.'},
{id:'squat-knee-drive',name:'Squat + Knee Drive',cat:'Glutes · Full Body',level:2,equipment:'Zuhause',muscles:'Glutes · Full Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Tief und kontrolliert beugen, kraftvoll aufrichten und abwechselnd ein Knie nach vorn oben führen.'},
{id:'lateral-lunge-drive',name:'Lateral Lunge + Knee Drive',cat:'Glutes · Full Body',level:2,equipment:'Zuhause',muscles:'Glutes · Full Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Seitlich weit aussteigen, Hüfte über das belastete Bein zurücksetzen und beim Aufrichten das freie Knie anheben.'},
{id:'bulgarian',name:'Bulgarian Split Squat',cat:'Glutes · Legs',level:2,equipment:'Zuhause',muscles:'Glutes · Legs',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Hinteren Fuß auf Sofa oder Stuhl ablegen. Über das vordere Bein kontrolliert tief gehen und hochdrücken.'},
{id:'reverse-lunge',name:'Reverse Lunge',cat:'Glutes · Legs',level:2,equipment:'Zuhause',muscles:'Glutes · Legs',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Einen großen Schritt zurücksetzen, vorderen Fuß voll belasten und über das vordere Bein wieder aufrichten.'},
{id:'stepup',name:'Step-up',cat:'Glutes · Legs',level:2,equipment:'Zuhause',muscles:'Glutes · Legs',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Auf eine stabile Stufe steigen und den Körper ohne Absprung vom Boden vollständig über das Arbeitsbein hochdrücken.'},
{id:'sumo-squat',name:'Sumo Squat',cat:'Glutes · Legs',level:2,equipment:'Zuhause',muscles:'Glutes · Legs',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Breiter Stand, Knie folgen den Fußspitzen. Hüfte kontrolliert absenken und kraftvoll aufrichten.'},
{id:'tempo-squat',name:'Tempo Squat',cat:'Glutes · Legs',level:2,equipment:'Zuhause',muscles:'Glutes · Legs',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Drei Sekunden absenken, unten kurz stabil bleiben und kontrolliert aufrichten.'},
{id:'sl-rdl',name:'Single Leg RDL',cat:'Glutes · Hamstrings',level:2,equipment:'Zuhause',muscles:'Glutes · Hamstrings',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Standbein leicht beugen, Hüfte weit nach hinten schieben und mit langem Rücken über die Hüfte wieder aufrichten.'},
{id:'kickstand-rdl',name:'Kickstand RDL',cat:'Glutes · Hamstrings',level:2,equipment:'Zuhause',muscles:'Glutes · Hamstrings',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Ein Bein trägt fast das gesamte Gewicht, die andere Fußspitze dient nur als Stütze. Hüfte weit nach hinten führen.'},
{id:'hip-thrust',name:'Hip Thrust',cat:'Glutes',level:2,equipment:'Zuhause',muscles:'Glutes',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Schulterblätter an Sofa oder Bettkante. Becken über die Fersen strecken und oben das Gesäß kräftig anspannen.'},
{id:'single-hip-thrust',name:'Single Leg Hip Thrust',cat:'Glutes',level:2,equipment:'Zuhause',muscles:'Glutes',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Schulterblätter erhöht, ein Bein frei. Becken einbeinig strecken und dabei gerade halten.'},
{id:'glute-bridge',name:'Glute Bridge',cat:'Glutes',level:2,equipment:'Zuhause',muscles:'Glutes',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Fersen nah zum Gesäß, Becken anheben und oben Gesäß fest anspannen ohne ins Hohlkreuz zu gehen.'},
{id:'single-bridge',name:'Single Leg Glute Bridge',cat:'Glutes',level:2,equipment:'Zuhause',muscles:'Glutes',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Eine Ferse nah zum Gesäß, anderes Bein frei. Becken gerade einbeinig anheben und oben kurz halten.'},
{id:'frog-pump',name:'Frog Pump',cat:'Glutes',level:2,equipment:'Zuhause',muscles:'Glutes',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Fußsohlen zusammen, Knie nach außen. Becken anheben und jede Wiederholung mit deutlicher Gesäßanspannung beenden.'},
{id:'bridge-march',name:'Glute Bridge March',cat:'Glutes · Core',level:2,equipment:'Zuhause',muscles:'Glutes · Core',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Becken in der Bridge oben halten und abwechselnd einen Fuß wenige Zentimeter anheben, ohne das Becken zu verdrehen.'},
{id:'pushup',name:'Push-up',cat:'Push · Upper Body',level:2,equipment:'Zuhause',muscles:'Push · Upper Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Körper als feste Linie halten. Brust kontrolliert absenken und den Boden aktiv wegdrücken.'},
{id:'incline-pushup',name:'Incline Push-up',cat:'Push · Upper Body',level:2,equipment:'Zuhause',muscles:'Push · Upper Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Hände erhöht auf stabilem Tisch oder Sofa. Körper gerade halten und Brust kontrolliert zur Kante führen.'},
{id:'decline-pushup',name:'Decline Push-up',cat:'Push · Upper Body',level:2,equipment:'Zuhause',muscles:'Push · Upper Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Füße leicht erhöht, Hände am Boden. Körper stabil halten und kontrolliert drücken.'},
{id:'pike-pushup',name:'Pike Push-up',cat:'Push · Upper Body',level:2,equipment:'Zuhause',muscles:'Push · Upper Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Hüfte hochschieben, Kopf kontrolliert zwischen den Händen absenken und den Boden kräftig wegdrücken.'},
{id:'band-row',name:'Resistance Band Row',cat:'Pull · Upper Body',level:2,equipment:'Zuhause',muscles:'Pull · Upper Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Band sicher vor dir fixieren. Ellbogen nach hinten ziehen und Schulterblätter kontrolliert zusammenführen.'},
{id:'band-pulldown',name:'Resistance Band Pulldown',cat:'Pull · Upper Body',level:2,equipment:'Zuhause',muscles:'Pull · Upper Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Band sicher über Kopfhöhe fixieren. Ellbogen nach unten zum Körper ziehen und langsam zurückführen.'},
{id:'band-pullapart',name:'Resistance Band Pull-Apart',cat:'Pull · Upper Body',level:2,equipment:'Zuhause',muscles:'Pull · Upper Body',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Band auf Brusthöhe halten und mit gestreckten Armen auseinanderziehen, bis die Schulterblätter zusammenkommen.'},
{id:'dead-bug',name:'Dead Bug',cat:'Core Stability',level:2,equipment:'Zuhause',muscles:'Core Stability',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Rücken stabil am Boden halten. Gegengleichen Arm und Bein langsam strecken, ohne dass sich der untere Rücken löst.'},
{id:'side-plank',name:'Side Plank',cat:'Core Stability',level:2,equipment:'Zuhause',muscles:'Core Stability',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Schulter, Becken und Füße in einer Linie halten. Becken aktiv vom Boden wegdrücken.'},
{id:'bear-tap',name:'Bear Plank Shoulder Tap',cat:'Core Stability',level:2,equipment:'Zuhause',muscles:'Core Stability',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Knie knapp über dem Boden halten und abwechselnd die gegenüberliegende Schulter berühren, ohne das Becken zu verdrehen.'},
{id:'plank-drag',name:'Plank Reach',cat:'Core Stability',level:2,equipment:'Zuhause',muscles:'Core Stability',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Aus stabiler Plankposition einen Arm langsam nach vorn strecken. Becken und Brust bleiben möglichst ruhig.'},
{id:'bird-dog',name:'Bird Dog',cat:'Core Stability',level:2,equipment:'Zuhause',muscles:'Core Stability',steps:['Stabile Ausgangsposition einnehmen.','Bewegung kontrolliert und im schmerzfreien Bewegungsradius ausführen.','Spannung halten und sauber in die Ausgangsposition zurückkehren.'],cue:'Im Vierfüßler gegengleichen Arm und Bein lang ausstrecken, ohne Becken oder Rücken zu verdrehen.'},
];
const phaseFor=w=>w<=2?['BASELINE','Technik & Ausgangsniveau · 30–35 Min.']:w<=4?['REPS','Wiederholungen steigern · 30–40 Min.']:w===5?['VOLUME','Hauptübungen priorisieren · 35–40 Min.']:w<=7?['PROGRESSION I','Nächste Stufe verdienen · 35–40 Min.']:w===8?['CONSOLIDATE','Neue Stufe festigen · 35–40 Min.']:w<=10?['PROGRESSION II','Schwierigkeit weiter steigern · 35–45 Min.']:w===11?['QUALITY','Volumen auf erreichtem Niveau · 35–45 Min.']:w===12?['PEAK','Höchste saubere Belastung · 40–45 Min.']:['BENCHMARK','Fortschritt sichtbar machen · 35–45 Min.'];
const repFor=w=>w<=2?'8–10':w<=4?'10–12':w===5?'10–12':w<=8?'8–12':w<=11?'10–15':w===12?'8–12':'AMRAP sauber';
const coreFor=w=>w<=2?'8–10/Seite':w<=5?'10–12/Seite':w<=9?'12–15/Seite':w<=12?'12–15/Seite':'AMRAP sauber';
const holdFor=w=>w<=2?'30 s/Seite':w<=5?'35–40 s/Seite':w<=9?'40–45 s/Seite':w<=12?'45–50 s/Seite':'max. sauber';
const setsFor=w=>w===1?2:w===5||w===11||w===12?4:3;
const main=(w,target)=>`${setsFor(w)}×${target}`;
const normal=(w,target)=>`${w===1?2:3}×${target}`;
const planned={
 squat:w=>w<=2?'reverse-lunge':w<=5?'tempo-squat':w<=8?'bulgarian':'bulgarian',
 hinge:w=>w<=3?'kickstand-rdl':'sl-rdl',
 bridge:w=>w<=2?'glute-bridge':w<=5?'hip-thrust':w<=8?'single-bridge':'single-hip-thrust',
 push:w=>w<=2?'incline-pushup':w<=8?'pushup':'decline-pushup',
 pull:w=>w<=6?'band-row':'band-pulldown',
 core:w=>w<=2?'bird-dog':w<=5?'dead-bug':w<=8?'bear-tap':'plank-drag'
};
export const weeks=Array.from({length:13},(_,i)=>{const w=i+1,[title,focus]=phaseFor(w),rep=repFor(w);return {week:w,date:'',title,focus,days:[
 {name:'A · SQUAT + GLUTES',items:[['reverse-lunge-drive',normal(w,w<3?'8/Seite':'10/Seite')],[planned.squat(w),main(w,rep+'/Seite')],[planned.pull(w),normal(w,rep)],[planned.bridge(w),main(w,rep)],[planned.core(w),normal(w,coreFor(w))]]},
 {name:'B · HINGE + GLUTES',items:[['stepup-drive',normal(w,w<3?'8/Seite':'10/Seite')],[planned.hinge(w),main(w,rep+'/Seite')],[planned.push(w),normal(w,rep)],[planned.bridge(w),main(w,rep)],[w<=5?'side-plank':planned.core(w),normal(w,w<=5?holdFor(w):coreFor(w))]]},
 {name:'C · GLUTES + CORE',items:[['squat-knee-drive',normal(w,w<3?'8/Seite':'10/Seite')],[planned.squat(w),main(w,rep+'/Seite')],[planned.pull(w),normal(w,rep)],[planned.bridge(w),main(w,rep)],[planned.core(w),normal(w,coreFor(w))]]}
]}});
export const intro={title:'',focus:'',days:[]};
export const rules=[];
export const glutesCoreProgram={id:'unused',name:'',subtitle:'',weeks:[]};